version: '2.0'

services:

  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MODEL: "RAK2287"
      TTN_REGION: "nam1"
      TC_URI: "https://tts.etowah.cloud:8885"
      CUPS_URI: "https://tts.etowah.cloud:443"
      CUPS_KEY: ""
      TC_KEY: ""
      CUPS_TRUST: "-----BEGIN CERTIFICATE----- MIICETCCAbegAwIBAgIUaMHk3ivtzl6k5JkqXXjKJkGlQKcwCgYIKoZIzj0EAwIwSjELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0dlb3JnaWExEjAQBgNVBAcTCURhaGxvbmVnYTEVMBMGA1UEChMMVUwgU29mdHdvcmtzMB4XDTIyMDgwNTE3MTgwMFoXDTIzMDgwNTE3MTgwMFowSjELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0dlb3JnaWExEjAQBgNVBAcTCURhaGxvbmVnYTEVMBMGA1UEChMMVUwgU29mdHdvcmtzMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErpgLAJ4HN3rI3r80FXSTUE2iKc/W4MulF8/YV51pKMr0IRJ0Nk3v19y7n96sAc/HmBV3ZdDFD/CdeZSUuWfPHKN7MHkwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVNt0148lmDOuk8MCJVWuVNlIpvjAbBgNVHREEFDASghB0dHMuZXRvd2FoLmNsb3VkMAoGCCqGSM49BAMCA0gAMEUCIQCBgeuqjyeaPw7uxPXZig323To27M8DGLruplBeuOok2wIgftsABD1DvkMkgQvFxUA25nh95AnZSShZZrXQRmVO150= -----END CERTIFICATE-----"
      TC_TRUST: "-----BEGIN CERTIFICATE----- MIICETCCAbegAwIBAgIUaMHk3ivtzl6k5JkqXXjKJkGlQKcwCgYIKoZIzj0EAwIwSjELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0dlb3JnaWExEjAQBgNVBAcTCURhaGxvbmVnYTEVMBMGA1UEChMMVUwgU29mdHdvcmtzMB4XDTIyMDgwNTE3MTgwMFoXDTIzMDgwNTE3MTgwMFowSjELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0dlb3JnaWExEjAQBgNVBAcTCURhaGxvbmVnYTEVMBMGA1UEChMMVUwgU29mdHdvcmtzMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErpgLAJ4HN3rI3r80FXSTUE2iKc/W4MulF8/YV51pKMr0IRJ0Nk3v19y7n96sAc/HmBV3ZdDFD/CdeZSUuWfPHKN7MHkwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVNt0148lmDOuk8MCJVWuVNlIpvjAbBgNVHREEFDASghB0dHMuZXRvd2FoLmNsb3VkMAoGCCqGSM49BAMCA0gAMEUCIQCBgeuqjyeaPw7uxPXZig323To27M8DGLruplBeuOok2wIgftsABD1DvkMkgQvFxUA25nh95AnZSShZZrXQRmVO150= -----END CERTIFICATE-----"
